### ISSUE TITLE
[BUG] Autopickup Not Working

### ISSUE THREAD

**Issue by SirCraftypants** [LoneDev6/Issues-EpicBackpacks#2]
**Describe the bug**
another user reported that the Auto Pickup wasn't working so i tested it myself with the latest EBP and LoneLibs.

I'm opped and also have all the permissions, everything works accept for the auto pickup.

**To Reproduce**
1. fill up inventory and action bar with items and an empty backpack
2. drop items on floor that are not in inventory.
3. enable autopickup
4. attempt to pickup items.

**Expected behavior**
unable to auto pickup items.

**Info (please complete the following information):**
 - Server version: (example: paper 1.16.4)
 - Client version: (example: Minecraft 1.16.4)
 - Plugin version: Lonelibs 1.0.6   and Epic Backpacks 1.2.6

**Additional context**
No errors in console, just not working.

**Comment by LoneDev6** [comment]
Sadly when the inventory is full I cannot make the autopickup working.
Minecraft server doesn't send any pickup info to the game if the inventory is full so I cannot make this working, it's a problem that every backpack plugin with autopickup has.

I hope you understand, thanks for your patience

**Comment by SirCraftypants** [comment]
Ok, no problem, can't create miracles. I think it do good idea to remove it though so not to cause confusion, meaning less issues for you to be contacted about.
